M48
; DRILL file {KiCad 9.0.2} date 2025-08-07T20:28:27-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-07T20:28:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X143.31Y-56.89
X143.31Y-65.69
T2
X125.9Y-142.4
X136.3Y-34.6
X146.5Y-142.4
X150.7Y-34.6
M30
